mutation MyMutation($pubPointMetadataDesc: String!, $pubPointMetadataTags: String!, $pubPointMetadataTitle: String!, $publishPoint: String!, $videoId: Int!, $pubPointScheduleId) {
    createPubPointMetadatum(input: {pubPointMetadatum: {pubPointMetadataDesc: $pubPointMetadataDesc, pubPointMetadataTags: $pubPointMetadataTags, pubPointMetadataTitle: $pubPointMetadataTitle}})
    {
      pubPointMetadatum{
        pubPointMetadataId
      }
    }
  }

mutation MyMutation($pubPointMetadataDesc: String!, $pubPointMetadataId: Int!, $pubPointMetadataTags: String!, $pubPointMetadataTitle: String!) {
    updatePubPointMetadatum(input: {patch: {pubPointMetadataDesc: $pubPointMetadataDesc, pubPointMetadataId: $pubPointMetadataId, pubPointMetadataTags: $pubPointMetadataTags, pubPointMetadataTitle: $pubPointMetadataTitle}, pubPointMetadataId: $pubPointMetadataId}) {
      clientMutationId
    }
  }