let data_string = {
    "videos": {
        "reccount": ["10536"],
        "link": [{
            "$": {
                "type": "application/xml",
                "rel": "next",
                "href": "/videos/?sort_order=DESC&start=20&size=20"
            }
        }],
        "video": [{
            "record_id": ["2573648"],
            "season": ["6"],
            "episode_long_description": ["Olivia the Ostrich has fallen in to the canyon! The pups need to work together to lift her to safety, while keeping her soon-to-hatch eggs warm."],
            "episode_short_description": ["Olivia the Ostrich has fallen in to the canyon!"],
            "long_description": ["Olivia the Ostrich has fallen in to the canyon! The pups need to work together to lift her to safety, while keeping her soon-to-hatch eggs warm."],
            "short_description": ["Olivia the Ostrich has fallen in to the canyon!"],
            "duration": ["12:10"],
            "brightcove_ref_id": ["6055898284001"],
            "video_asset_id": ["127894DV"],
            "first_air_date": ["2019-07-15T07:14:59-04:00"],
            "last_air_date": ["2019-08-19T07:14:03-04:00"],
            "program_asset_id": ["2338"],
            "episode_asset_id": ["127894"],
            "is_captioned": ["1"],
            "is_desc_video": ["1"],
            "is_desc_video_text": ["0"],
            "keywords": ["dog|friendship|Adventure Bay|ostrich|baby|egg|soon to hatch|canyon|rescue|help|puppy|hero|save|Marshall|Rubble|Chase|Rocky|Zuma|Skye|Everest|Tracker"],
            "narrative_themes": [" "],
            "group": ["Kids"],
            "born_date": ["2019-07-10T10:00:00-04:00"],
            "kill_date": ["2019-08-17T16:32:00-04:00"],
            "strand": ["Preschool|School-Age"],
            "alpha_title": ["Pups Save the Baby Ostriches"],
            "trans_title": ["pups-save-the-baby-ostriches"],
            "title": ["Pups Save the Baby Ostriches"],
            "episode_title": ["Pups Save the Baby Ostriches"],
            "created_on": ["2019-07-02T19:00:26-04:00"],
            "updated_on": ["2019-08-19T07:35:08-04:00"],
            "is_documentary": ["0"],
            "is_archive": ["0"],
            "license_start": ["2019-05-18T08:00:01-04:00"],
            "license_end": ["2023-05-17T00:00:00-04:00"],
            "is_promo": ["0"],
            "program_order": ["37"]
        }, {
            "record_id": ["2546337"],
            "season": ["1"],
            "episode_long_description": ["Five and friends set off on a rhyming romp through field and forest but they keep getting mixed up! Learn how to keep numbers in order and find missing numbers with the Numberblocks."],
            "episode_short_description": ["Five and friends set off on a rhyming romp."],
            "long_description": ["Five and friends set off on a rhyming romp through field and forest but they keep getting mixed up! Learn how to keep numbers in order and find missing numbers with the Numberblocks."],
            "short_description": ["Five and friends set off on a rhyming romp."],
            "duration": ["5:00"],
            "brightcove_ref_id": ["5995463925001"],
            "video_asset_id": ["125246X"],
            "first_air_date": ["2019-05-07T08:34:20-04:00"],
            "last_air_date": ["2019-08-19T06:52:00-04:00"],
            "program_asset_id": ["4676"],
            "episode_asset_id": ["125246"],
            "is_captioned": ["1"],
            "is_desc_video": ["0"],
            "is_desc_video_text": ["1"],
            "keywords": ["math|numbers|song|five|rhyme|Number 5|music|play|explore|discover"],
            "narrative_themes": [" "],
            "group": ["Kids"],
            "born_date": ["2019-02-04T09:00:00-05:00"],
            "kill_date": ["2019-03-31T09:00:00-05:00"],
            "strand": ["Preschool"],
            "alpha_title": ["Off We Go"],
            "trans_title": ["off-we-go"],
            "title": ["Off We Go"],
            "episode_title": ["Off We Go"],
            "created_on": ["2019-01-21T17:10:20-05:00"],
            "updated_on": ["2019-08-19T07:05:08-04:00"],
            "is_documentary": ["0"],
            "is_archive": ["0"],
            "license_start": ["2019-02-01T00:00:00-05:00"],
            "license_end": ["2023-01-31T00:00:00-05:00"],
            "is_promo": ["0"],
            "program_order": ["9"]
        }, {
            "record_id": ["2491157"],
            "season": ["1"],
            "episode_long_description": ["Tee and Mo are having a Dancing Day! That is, until Tee notices someone laughing at them. Can Mo get Tee to dance like no-one's watching again?"],
            "episode_short_description": ["Tee and Mo are having a Dancing Day! That is, until Tee notices someone laughing at them."],
            "long_description": ["The clues: A knitted sock with the word Torvik inside, a small rock, a wooden dragonhead The file label: \"It Was Them\" The investigation: The sock clue leads Kyla to a group of re-enactors called Torvik. After learning some basic sword fighting moves, she discovers that the sock was made using a knitting technique called nalbinding, which is how Vikings made socks and mittens. The kids wonder if this mystery might be about Vikings. E.B. heads to a Viking archeology lab to investigate the rock. Turns out It's a piece of slag iron, which is what was left over after the Vikings made iron. He helps forge a rivet just like the Vikings did for their awesome ships! Kyla discovers there's a Viking ship at sea right now. It's the biggest modern day Viking ship ever built. She video chats with a crewmember aboard the ship and finds out that the dragonhead clue from the mystery file is almost exactly like the dragon figurehead on this ship. Vikings used to put dragon figureheads on their shi"],
            "short_description": ["Tee and Mo are having a Dancing Day! That is, until Tee notices someone laughing at them."],
            "duration": ["7:00"],
            "brightcove_ref_id": ["5775357754001"],
            "video_asset_id": ["122009X"],
            "first_air_date": ["2018-11-06T10:09:31-05:00"],
            "last_air_date": ["2019-08-19T06:44:45-04:00"],
            "program_asset_id": ["3719"],
            "episode_asset_id": ["122009"],
            "is_captioned": ["1"],
            "is_desc_video": ["0"],
            "is_desc_video_text": ["1"],
            "keywords": ["Monkey|mother|son|dance|music|laughing|toddler|family|home|discover|play|learn|feelings|Tee|Mo"],
            "narrative_themes": [" "],
            "group": ["Kids"],
            "born_date": ["2019-05-11T09:00:00-04:00"],
            "kill_date": ["2019-06-10T15:03:22-04:00"],
            "strand": ["Preschool"],
            "alpha_title": ["Dance"],
            "trans_title": ["dance"],
            "title": ["Dance"],
            "episode_title": ["Dance"],
            "created_on": ["2018-03-13T16:20:28-04:00"],
            "updated_on": ["2019-08-19T07:05:08-04:00"],
            "is_documentary": ["0"],
            "is_archive": ["0"],
            "license_start": ["2018-03-11T07:08:00-04:00"],
            "license_end": ["2024-03-10T00:00:00-05:00"],
            "is_promo": ["0"],
            "program_order": ["48"]
        }, {
            "record_id": ["2512852"],
            "season": ["1"],
            "episode_long_description": ["When their soccer ball deflates, Ping and Pong make it into a Brazilian instrument: a cuica and a soccer game turns into Samba!"],
            "episode_short_description": ["Ping and Pong turn a soccer game turns into the Samba!"],
            "long_description": ["When their soccer ball deflates, Ping and Pong make it into a Brazilian instrument: a cuica and a soccer game turns into Samba!"],
            "short_description": ["Ping and Pong turn a soccer game turns into the Samba!"],
            "duration": ["7:00"],
            "brightcove_ref_id": ["5857852469001"],
            "video_asset_id": ["122795X"],
            "first_air_date": ["2018-11-21T06:37:24-05:00"],
            "last_air_date": ["2019-08-19T06:37:24-04:00"],
            "program_asset_id": ["4005"],
            "episode_asset_id": ["122795"],
            "is_captioned": ["1"],
            "is_desc_video": ["0"],
            "is_desc_video_text": ["1"],
            "keywords": ["Ping and Friends|preschool|Samba|soccer|soccer ball|deflates|cuica|animated|music|friendship|cooperation|problem solving|animals|instuments|melody|rhythm|sounds|Matilda|Ping|Pong|Mr. Prickles|dance|sing"],
            "narrative_themes": [" "],
            "group": ["Kids"],
            "born_date": ["2019-11-12T09:00:00-05:00"],
            "kill_date": ["2019-11-30T11:23:06-04:00"],
            "strand": ["Preschool"],
            "alpha_title": ["Kickups to Samba, From"],
            "trans_title": ["from-kickups-to-samba"],
            "title": ["From Kickups to Samba"],
            "episode_title": ["From Kickups to Samba"],
            "created_on": ["2018-07-12T17:40:41-04:00"],
            "updated_on": ["2019-08-19T07:05:07-04:00"],
            "is_documentary": ["0"],
            "is_archive": ["0"],
            "license_start": ["2018-11-12T06:37:00-05:00"],
            "license_end": ["2024-11-11T00:00:00-05:00"],
            "is_promo": ["0"],
            "program_order": ["14"]
        }, {
            "record_id": ["2406969"],
            "season": ["2"],
            "episode_long_description": ["Permafrost is an underground layer of soil or rock that stays frozen all year round, but in recent years it's been thawing. In some parts of the north the thaw has created sinkholes and is disrupting the natural order of life. The full force of climate change is visible at Polar Bear Provincial Park in Ontario's far north."],
            "episode_short_description": ["Climate change is thawing permafrost in northern Ontario."],
            "long_description": ["Permafrost is an underground layer of soil or rock that stays frozen all year round, but in recent years it's been thawing. In some parts of the north the thaw has created sinkholes and is disrupting the natural order of life. The full force of climate change is visible at Polar Bear Provincial Park in Ontario's far north."],
            "short_description": ["Climate change is thawing permafrost in northern Ontario."],
            "duration": ["4:20"],
            "brightcove_ref_id": ["5222182511001"],
            "video_asset_id": ["380915X"],
            "first_air_date": ["2017-01-03T19:51:04-05:00"],
            "last_air_date": ["2019-08-19T05:54:40-04:00"],
            "program_asset_id": ["3809"],
            "episode_asset_id": ["380915"],
            "is_captioned": ["1"],
            "is_desc_video": ["0"],
            "is_desc_video_text": ["1"],
            "keywords": ["Climate Watch Shorts|Climate change|Permafrost|Polar Bear Provincial Park|Climate Watch"],
            "narrative_themes": ["Climate Watch"],
            "group": ["Adult"],
            "born_date": ["2019-12-07T06:00:00-05:00"],
            "kill_date": ["2019-12-31T23:59:00-05:00"],
            "strand": ["Environment"],
            "alpha_title": ["Climate Watch Shorts: Melting permafrost"],
            "trans_title": ["climate-watch-shorts-melting-permafrost"],
            "title": ["Climate Watch Shorts: Melting permafrost"],
            "episode_title": ["Climate Watch Shorts: Melting permafrost"],
            "created_on": ["2016-11-21T12:40:35-05:00"],
            "updated_on": ["2019-08-19T06:05:07-04:00"],
            "is_documentary": ["0"],
            "is_archive": ["0"],
            "license_start": ["1800-01-01T00:00:00-05:00"],
            "license_end": ["2999-01-01T00:00:00-05:00"],
            "is_promo": ["0"],
            "program_order": ["15"]
        }, {
            "record_id": ["2473188"],
            "season": ["4"],
            "episode_long_description": ["Gina and Melanie find Dr. Kesler going through withdrawal, forcing Gina to step in and make a tough call. Gary's unorthodox approach to a reconciliation session backfires. Charlie's discovery of Eddy's and Tara's collusion ends up very badly for an avian dream home. Helvi's and Nancy's relationship reaches a breaking point. Farida lays down the law with Krista's parents, and Melanie helps her elderly abuse patient regain some personal autonomy."],
            "episode_short_description": ["Decisions, decisions, decisions. Gina and Melanie find Dr. Kesler going through withdrawal, forcing Gina to step in and make a tough call."],
            "long_description": ["Gina and Melanie find Dr. Kesler going through withdrawal, forcing Gina to step in and make a tough call. Gary's unorthodox approach to a reconciliation session backfires. Charlie's discovery of Eddy's and Tara's collusion ends up very badly for an avian dream home. Helvi's and Nancy's relationship reaches a breaking point. Farida lays down the law with Krista's parents, and Melanie helps her elderly abuse patient regain some personal autonomy."],
            "short_description": ["Decisions, decisions, decisions. Gina and Melanie find Dr. Kesler going through withdrawal, forcing Gina to step in and make a tough call."],
            "duration": ["24:00"],
            "brightcove_ref_id": ["5686394509001"],
            "video_asset_id": ["122861DV"],
            "first_air_date": ["2018-01-23T21:00:00-05:00"],
            "last_air_date": ["2019-08-19T05:30:00-04:00"],
            "program_asset_id": ["1623"],
            "episode_asset_id": ["122861"],
            "is_captioned": ["1"],
            "is_desc_video": ["1"],
            "is_desc_video_text": ["0"],
            "keywords": ["Hard Rock Medical|Northern Ontario"],
            "narrative_themes": [" "],
            "group": ["Adult"],
            "born_date": ["2019-01-23T23:59:00-05:00"],
            "kill_date": ["2019-12-31T23:59:00-05:00"],
            "strand": ["Drama"],
            "alpha_title": ["Ep. 7 - Breaking Point"],
            "trans_title": ["ep-7-breaking-point"],
            "title": ["Ep. 7 - Breaking Point"],
            "episode_title": ["Ep. 7 - Breaking Point"],
            "created_on": ["2017-11-09T15:50:15-05:00"],
            "updated_on": ["2019-08-19T05:35:07-04:00"],
            "is_documentary": ["0"],
            "is_archive": ["0"],
            "license_start": ["2018-01-02T21:00:00-05:00"],
            "license_end": ["2025-01-01T00:00:00-05:00"],
            "is_promo": ["0"],
            "program_order": ["37"]
        }, {
            "record_id": ["2565011"],
            "season": ["2"],
            "episode_long_description": ["Cobalt was once a booming town built on the silver mining industry. Just as the silver ran out, the town was ravaged by a fire in 1977 leaving it a shell of its former self.  Now, Cobalt is poised for a renaissance thanks to its namesake, cobalt."],
            "episode_short_description": ["Cobalt was once a booming town built on the silver mining industry. Just as the silver ran out, the town was ravaged by a fire in 1977.  Now, Cobalt is poised for a renaissance thanks to its namesake, cobalt."],
            "long_description": ["Cobalt was once a booming town built on the silver mining industry. Just as the silver ran out, the town was ravaged by a fire in 1977 leaving it a shell of its former self.  Now, Cobalt is poised for a renaissance thanks to its namesake, cobalt."],
            "short_description": ["Cobalt was once a booming town built on the silver mining industry. Just as the silver ran out, the town was ravaged by a fire in 1977.  Now, Cobalt is poised for a renaissance thanks to its namesake, cobalt."],
            "duration": ["4:40"],
            "brightcove_ref_id": ["6040790736001"],
            "video_asset_id": ["125973X"],
            "first_air_date": ["2019-06-28T21:51:36-04:00"],
            "last_air_date": ["2019-08-19T04:53:48-04:00"],
            "program_asset_id": ["3902"],
            "episode_asset_id": ["125973"],
            "is_captioned": ["1"],
            "is_desc_video": ["0"],
            "is_desc_video_text": ["1"],
            "keywords": ["Cobalt|Ontario|Mining"],
            "narrative_themes": ["Shared Values"],
            "group": ["Adult"],
            "born_date": ["2019-05-31T05:00:00-04:00"],
            "kill_date": ["2019-06-29T23:59:59-04:00"],
            "strand": ["Canadian Docs"],
            "alpha_title": ["Main Street Ontario: Cobalt"],
            "trans_title": ["main-street-ontario-cobalt"],
            "title": ["Main Street Ontario: Cobalt"],
            "episode_title": ["Main Street Ontario: Cobalt"],
            "created_on": ["2019-04-26T12:40:36-04:00"],
            "updated_on": ["2019-08-19T05:05:07-04:00"],
            "is_documentary": ["0"],
            "is_archive": ["0"],
            "license_start": ["2019-05-31T05:00:00-04:00"],
            "license_end": ["2029-05-30T00:00:00-04:00"],
            "is_promo": ["0"],
            "program_order": ["12"]
        }, {
            "record_id": ["2577989"],
            "season": ["1"],
            "episode_long_description": ["Veteran politician Ian Waddell talks about his time in federal and provincial politics, and why championing progressive policies has been his life's work."],
            "episode_short_description": ["Ian Waddell discusses his time in politics and as an advocate for progressive policies."],
            "long_description": ["The Canadian Wrestling Federation is about more than just showdowns in the ring: as northeastern Ontario Hubs reporter Claude Sharma learns, when it visits Indigenous communities across the country, it also offers wrestling bootcamps and educational workshops on issues such as drug and alcohol abuse and suicide prevention."],
            "short_description": ["Northeastern Ontario Hub reporter Claude Sharma discusses how the Canadian Wrestling Federation is helping Indigenous communities learn how to deal with issues such as bullying."],
            "duration": ["1:59"],
            "brightcove_ref_id": ["6073737833001"],
            "video_asset_id": ["2570698"],
            "first_air_date": ["2019-08-16T20:00:02-04:00"],
            "last_air_date": ["2019-08-19T05:00:02-04:00"],
            "program_asset_id": ["2790"],
            "episode_asset_id": ["172959"],
            "is_captioned": ["1"],
            "is_desc_video": ["0"],
            "is_desc_video_text": ["0"],
            "keywords": ["Canadian Wrestling Federation|Indigenous|Ontario Hubs"],
            "narrative_themes": [" "],
            "group": ["Adult"],
            "born_date": ["2019-08-16T18:30:45-04:00"],
            "kill_date": ["2019-09-16T10:17:54-04:00"],
            "strand": ["Current Affairs"],
            "alpha_title": ["Ontario Hubs: Wrestling for Success"],
            "trans_title": ["ontario-hubs-wrestling-for-success"],
            "title": ["Ontario Hubs: Wrestling for Success"],
            "episode_title": ["The Agenda in the Summer: Ian Waddell; Ontario Hubs"],
            "created_on": ["2019-08-13T13:00:27-04:00"],
            "updated_on": ["2019-08-19T05:05:07-04:00"],
            "is_documentary": ["0"],
            "is_archive": ["0"],
            "license_start": ["1800-01-01T00:00:00-05:00"],
            "license_end": ["2999-01-01T00:00:00-05:00"],
            "is_promo": ["0"],
            "program_order": ["389"]
        }, {
            "record_id": ["2577990"],
            "season": ["1"],
            "episode_long_description": ["Veteran politician Ian Waddell talks about his time in federal and provincial politics, and why championing progressive policies has been his life's work."],
            "episode_short_description": ["Ian Waddell discusses his time in politics and as an advocate for progressive policies."],
            "long_description": ["Ian Waddell, a former NDP MP and former B.C. MLA talks to Nam Kiwanuka about his memoir, \"Take the Torch.\" Among Waddell's proudest moments in politics was in drafting Section 35 of the Canadian Constitution, which ensured the rights of Indigenous people. From pipelines to cultural policy, Ian Waddell has championed progressive policy throughout his career in and out of politics."],
            "short_description": ["Nam Kiwanuka talks to Ian Waddell about his book, \"Take The Torch: A Political Memoir.\""],
            "duration": ["27:08"],
            "brightcove_ref_id": ["6073811878001"],
            "video_asset_id": ["2562556"],
            "first_air_date": ["2019-08-16T20:00:01-04:00"],
            "last_air_date": ["2019-08-19T05:00:01-04:00"],
            "program_asset_id": ["2790"],
            "episode_asset_id": ["172959"],
            "is_captioned": ["1"],
            "is_desc_video": ["0"],
            "is_desc_video_text": ["0"],
            "keywords": ["NDP|Ian Waddell|B.C. politics"],
            "narrative_themes": [" "],
            "group": ["Adult"],
            "born_date": ["2019-08-16T18:30:45-04:00"],
            "kill_date": ["2019-09-16T10:17:54-04:00"],
            "strand": ["Current Affairs"],
            "alpha_title": ["Ian Waddell: A Life in Progressive Politics"],
            "trans_title": ["ian-waddell-a-life-in-progressive-politics"],
            "title": ["Ian Waddell: A Life in Progressive Politics"],
            "episode_title": ["The Agenda in the Summer: Ian Waddell; Ontario Hubs"],
            "created_on": ["2019-08-13T13:00:40-04:00"],
            "updated_on": ["2019-08-19T05:05:07-04:00"],
            "is_documentary": ["0"],
            "is_archive": ["0"],
            "license_start": ["1800-01-01T00:00:00-05:00"],
            "license_end": ["2999-01-01T00:00:00-05:00"],
            "is_promo": ["0"],
            "program_order": ["389"]
        }, {
            "record_id": ["2229928"],
            "season": ["1"],
            "episode_long_description": ["An unlikely tale of joy and inspiration, this documentary tells the story of Totonel, a nine-year-old Roma boy living in the poorest area of Romania's capital. His mother has been imprisoned for drug dealing and Totonel has never attended school. The film follows the blossoming of his creative life and self-confidence as he starts to attend an alternative education club. He proves to be a gifted dancer and embraces sports, English and math."],
            "episode_short_description": ["This unlikely tale of joy and inspiration follows a nine-year-old Roma boy living in a Bucharest slum."],
            "long_description": ["An unlikely tale of joy and inspiration, this documentary tells the story of Totonel, a nine-year-old Roma boy living in the poorest area of Romania's capital. His mother has been imprisoned for drug dealing and Totonel has never attended school. The film follows the blossoming of his creative life and self-confidence as he starts to attend an alternative education club. He proves to be a gifted dancer and embraces sports, English and math."],
            "short_description": ["This unlikely tale of joy and inspiration follows a nine-year-old Roma boy living in a Bucharest slum."],
            "duration": ["1:36:39"],
            "brightcove_ref_id": ["5042141545001"],
            "video_asset_id": ["686226X"],
            "first_air_date": ["2016-08-24T21:00:00-04:00"],
            "last_air_date": ["2019-08-19T03:15:00-04:00"],
            "program_asset_id": ["686226"],
            "episode_asset_id": ["686226"],
            "is_captioned": ["1"],
            "is_desc_video": ["0"],
            "is_desc_video_text": ["1"],
            "keywords": ["Cultural Studies|Education"],
            "narrative_themes": [" "],
            "group": ["Adult"],
            "born_date": ["2019-08-24T23:49:00-04:00"],
            "kill_date": ["2019-08-30T23:59:00-04:00"],
            "strand": ["International Docs"],
            "alpha_title": ["Toto and His Sisters"],
            "trans_title": ["toto-and-his-sisters"],
            "title": ["Toto and His Sisters"],
            "episode_title": ["Toto and His Sisters"],
            "created_on": ["2014-09-26T17:10:04-04:00"],
            "updated_on": ["2019-08-19T03:35:07-04:00"],
            "is_documentary": ["1"],
            "is_archive": ["0"],
            "license_start": ["2016-08-24T21:00:00-04:00"],
            "license_end": ["2020-08-23T00:00:00-04:00"],
            "is_promo": ["0"],
            "program_order": ["1"]
        }, {
            "record_id": ["2532241"],
            "season": ["1"],
            "episode_long_description": ["As more women ascend the ranks of the male-dominated restaurant industry, and a younger generation challenges the brutal conditions once considered the norm, the rules of kitchen culture are being rewritten. Maya Gallus's documentary profiles seven female chefs at the vanguard of change in Toronto, London, and New York City."],
            "episode_short_description": ["Maya Gallus's documentary profiles seven female chefs who are rewriting the rules of kitchen culture in the male-dominated restaurant industry."],
            "long_description": ["As more women ascend the ranks of the male-dominated restaurant industry, and a younger generation challenges the brutal conditions once considered the norm, the rules of kitchen culture are being rewritten. Maya Gallus's documentary profiles seven female chefs at the vanguard of change in Toronto, London, and New York City."],
            "short_description": ["Maya Gallus's documentary profiles seven female chefs who are rewriting the rules of kitchen culture in the male-dominated restaurant industry."],
            "duration": ["1:11:15"],
            "brightcove_ref_id": ["5850472777001"],
            "video_asset_id": ["122868DV"],
            "first_air_date": ["2018-11-15T22:00:00-05:00"],
            "last_air_date": ["2019-08-19T02:00:00-04:00"],
            "program_asset_id": ["122868"],
            "episode_asset_id": ["122868"],
            "is_captioned": ["1"],
            "is_desc_video": ["1"],
            "is_desc_video_text": ["0"],
            "keywords": ["Gender|Social Issues"],
            "narrative_themes": ["The Food Chain|Shared Values"],
            "group": ["Adult"],
            "born_date": ["2019-11-15T22:01:00-05:00"],
            "kill_date": ["2019-12-13T23:59:00-05:00"],
            "strand": ["Canadian Docs"],
            "alpha_title": ["Heat: A Kitchen (R)evolution (Feature Version), The"],
            "trans_title": ["the-heat-a-kitchen-revolution-feature-version"],
            "title": ["The Heat: A Kitchen (R)evolution (Feature Version)"],
            "episode_title": ["The Heat: A Kitchen (R)evolution (Feature Version)"],
            "created_on": ["2018-11-07T17:40:15-05:00"],
            "updated_on": ["2019-08-19T02:05:09-04:00"],
            "is_documentary": ["1"],
            "is_archive": ["0"],
            "license_start": ["2018-11-15T22:00:00-05:00"],
            "license_end": ["2024-11-14T00:00:00-05:00"],
            "is_promo": ["0"],
            "program_order": ["1"]
        }, {
            "record_id": ["2551190"],
            "season": ["4"],
            "episode_long_description": ["In her university- level classes, Pam Palmater often sees students cry, get angry, or surprised at the realities of racism in Canada. In this web series called \"First Things First,\" Palmater explains how to handle emotions in difficult conversations."],
            "episode_short_description": ["Pam Palmater on the emotional reactions of students who are surprised at the realities of racism in Canada."],
            "long_description": ["In her university- level classes, Pam Palmater often sees students cry, get angry, or surprised at the realities of racism in Canada. In this web series called \"First Things First,\" Palmater explains how to handle emotions in difficult conversations."],
            "short_description": ["Pam Palmater on the emotional reactions of students who are surprised at the realities of racism in Canada."],
            "duration": ["3:40"],
            "brightcove_ref_id": ["6021678374001"],
            "video_asset_id": ["014585"],
            "first_air_date": ["2019-04-21T21:47:25-04:00"],
            "last_air_date": ["2019-08-19T01:54:29-04:00"],
            "program_asset_id": ["4742"],
            "episode_asset_id": ["014585"],
            "is_captioned": ["1"],
            "is_desc_video": ["0"],
            "is_desc_video_text": ["1"],
            "keywords": ["Reconciliation|Education|Indigenous Issues|Classroom|Pam Palmater"],
            "narrative_themes": [" "],
            "group": ["Adult"],
            "born_date": ["2019-04-03T06:00:00-04:00"],
            "kill_date": ["2019-05-02T11:33:11-04:00"],
            "strand": ["Current Affairs"],
            "alpha_title": ["do Indigenous topics cause such emotional discomfort?, Why"],
            "trans_title": ["why-do-indigenous-topics-cause-such-emotional-discomfort"],
            "title": ["Why do Indigenous topics cause such emotional discomfort?"],
            "episode_title": ["Why do Indigenous topics cause such emotional discomfort?"],
            "created_on": ["2019-02-14T19:10:40-05:00"],
            "updated_on": ["2019-08-19T02:05:08-04:00"],
            "is_documentary": ["0"],
            "is_archive": ["0"],
            "license_start": ["1800-01-01T00:00:00-05:00"],
            "license_end": ["1800-01-01T00:00:00-05:00"],
            "is_promo": ["0"],
            "program_order": ["2"]
        }]
    }
};
let resources = [];
let events = [];
let eventsForTaskView = [];
let eventsForCustomEventStyle = [];
let DemoData = {};
let video_array = data_string['videos']['video'];
let video_array_length = Object.keys(video_array).length;
let idNum = 0;
let finalDemoData = {};
//console.log(typeof video_array);
DemoData = {resources : [], events: [], eventsForTaskView: [], eventsForCustomEventStyle: []};
video_array.forEach(function (record) {
    
    
    let resources = DemoData.resources;
    resources.push({id: record.video_asset_id[0], name: `${record.video_asset_id[0]} - ${record.title}`, groupOnly: false});
    let events = DemoData.events;
    let publishDate = record.born_date[0];
    let killDate = record.kill_date[0];
    let publishDateFormated = `${publishDate.slice(0,10)} ${publishDate.slice(11,19)}`;
    let killDateFormated = `${killDate.slice(0,10)} ${killDate.slice(11,19)}`; 

    console.log((record.group[0]));

    if(record.group[0] == 'Adult'){
        events.push({id: idNum + 1,  start: publishDateFormated, end: killDateFormated, resourceId: record.video_asset_id[0], title: 'Brightcove', bgColor: '#f759ab'  });
    let eventsForTaskView = DemoData.eventsForTaskView;
    eventsForTaskView.push({id: idNum + 1,  start: publishDateFormated, end: killDateFormated, resourceId: record.video_asset_id[0], title: 'Brightcove', groupId: 1, groupName: 'Task1', bgColor: '#f759ab' });
    let eventsForCustomEventStyle = DemoData.eventsForCustomEventStyle;
    eventsForCustomEventStyle.push({id: idNum + 1,  start: publishDateFormated, end: killDateFormated, resourceId: record.video_asset_id[0], title: 'Brightcove', type: 1, bgColor: '#f759ab' });
    }else{
    events.push({id: idNum + 1,  start: publishDateFormated, end: killDateFormated, resourceId: record.video_asset_id[0], title: 'YouTube', bgColor: '#339AF0'  });
    let eventsForTaskView = DemoData.eventsForTaskView;
    eventsForTaskView.push({id: idNum + 1,  start: publishDateFormated, end: killDateFormated, resourceId: record.video_asset_id[0], title: 'YouTube', groupId: 1, groupName: 'Task1', bgColor: '#339AF0' });
    let eventsForCustomEventStyle = DemoData.eventsForCustomEventStyle;
    eventsForCustomEventStyle.push({id: idNum + 1,  start: publishDateFormated, end: killDateFormated, resourceId: record.video_asset_id[0], title: 'YouTube', type: 1, bgColor: '#339AF0' });
    }

    console.log(idNum);

    if (idNum == 19){
        events.push({
            id: 21,
            start: '2019-03-22 09:00:00',
            end: '2019-04-01 10:56:35',
            resourceId: '125969X',
            title: 'Brightcove',
            bgColor: '#f759ab',
        },
        {
            id: 22,
            start: '2019-03-22 09:00:00',
            end: '2019-04-01 10:56:35',
            resourceId: '122009X',
            title: 'Brightcove',
            bgColor: '#f759ab',
        })
        eventsForTaskView.push({
            id: 21,
            start: '2019-03-22 09:00:00',
            end: '2019-04-01 10:56:35',
            resourceId: '125969X',
            title: 'Brightcove',
            bgColor: '#f759ab',
        },
        {
            id: 22,
            start: '2019-03-22 09:00:00',
            end: '2019-04-01 10:56:35',
            resourceId: '122009X',
            title: 'Brightcove',
            bgColor: '#f759ab',
        })

        eventsForCustomEventStyle.push({
            id: 21,
            start: '2019-03-22 09:00:00',
            end: '2019-04-01 10:56:35',
            resourceId: '125969X',
            title: 'Brightcove',
            bgColor: '#f759ab',
        },
        {
            id: 22,
            start: '2019-03-22 09:00:00',
            end: '2019-04-01 10:56:35',
            resourceId: '122009X',
            title: 'Brightcove',
            bgColor: '#f759ab',
        })

    }

    idNum = idNum + 1;
})



//console.log(DemoData);

export default DemoData
